In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('student_performance.csv')

In [3]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [4]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [5]:
print("Shape of Dataset",df.shape)

Shape of Dataset (30, 13)

In [7]:
#no of rows
print("Shape of 5th Column", df.shape[0])
#no of columns
print("Shape of 5th Column", df.shape[1])
#shape of 5th column of dataset

Shape of 5th Column 30
Shape of 5th Column 13

In [9]:
print("Colums in dataset:",df.columns.tolist())

Colums in dataset: ['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [10]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [11]:
#checking missing values
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [14]:
import numpy as np
df.loc[df["math_score"] < 70, "math_score"] = np.nan
print(df.isnull().sum())

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               9
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [15]:
print("Departments in this Dataset:")
print(df["department"].unique())

Departments in this Dataset:
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [16]:
print("How many students per department:")
print(df["department"].value_counts())

How many students per department:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [18]:
print(df["gender"].unique())
print(df["gender"].value_counts())

['Male' 'Female']
gender
Male      15
Female    15
Name: count, dtype: int64

In [19]:
print(df["city"].unique())
print(df["city"].value_counts())

['Mumbai' 'Ahmedabad' 'Delhi' 'Hyderabad' 'Kochi' 'Pune' 'Bangalore'
 'Lucknow' 'Varanasi' 'Kolkata' 'Chennai' 'Jaipur' 'Mysore' 'Thrissur'
 'Bhopal' 'Agra' 'Patna' 'Nagpur' 'Dehradun' 'Chandigarh'
 'Thiruvananthapuram' 'Surat' 'Allahabad' 'Kanpur' 'Indore']
city
Kochi                 2
Lucknow               2
Thiruvananthapuram    2
Agra                  2
Kolkata               2
Hyderabad             1
Mumbai                1
Delhi                 1
Ahmedabad             1
Varanasi              1
Bangalore             1
Pune                  1
Jaipur                1
Mysore                1
Thrissur              1
Bhopal                1
Chennai               1
Patna                 1
Nagpur                1
Dehradun              1
Chandigarh            1
Surat                 1
Allahabad             1
Kanpur                1
Indore                1
Name: count, dtype: int64

In [21]:
cs_students=df[df['department']=='Computer Science']
print(len(cs_students))

13

In [35]:
cm=df[ (df['city']=='Chennai')  | (df['city']=='Mumbai')]
print(len(cm))
print(cm[['name','city','programming_score']])

2
            name     city  programming_score
0   Aarav Sharma   Mumbai                 91
10   Vikram Iyer  Chennai                 72

In [37]:
attendance=df[df['attendance_percentage']<=75]
print(attendance[['name','attendance_percentage']])

             name  attendance_percentage
5     Meera Joshi                     72
8    Rahul Mishra                     68
14    Ajay Tiwari                     75
16   Manoj Pandey                     65
20  Harish Pillai                     74
22   Sanjay Dubey                     70
27  Sunita Pillai                     73

In [42]:
df['total_score']=df['math_score']+df['science_score']+df['english_score']+df['programming_score']
top_student=df.loc[df['total_score'].idxmax()]
print("Top Student:")
print(top_student[['name','total_score']])
print("\n")
least_student=df.loc[df['total_score'].idxmin()]
print("Least Student:")
print(least_student[['name','total_score']])

Top Student:
name           Ananya Das
total_score         371.0
Name: 9, dtype: object


Least Student:
name           Kiran Kumar
total_score          247.0
Name: 6, dtype: object

MINI PROJECT : Student Data Explorer
# Objective:

Create a Student Performance Explorer using Pandas and Pythin to analyze student data and generate a detailed report.

# Dataset Columns:

name

gender

department

math_score

programming_score

attendance_percentage

total_score

# Tasks to perform:
1. Display Project title

 Print a formatte title with seperator lines

2. Dataset Overview

Display:

-Total number of students

-total number of columns

-number of unique departments

3. Department wise analysis

display the count of students in each department.

4. Score Analysis

Find and Display:

-highest math score

-lowest math score

-avg math score

-avg programming score

-avg attendance percentage

5. Gender wise Analysis

Calculate and display avg total score by gender

6. Top performers

Display top 5 students based on total score.

Show:

-Student name

-Department

-total score

7. Attendance Analysis

Find students whose attendance is below 75%

Display:

-Name

-Department

-Atendance Percentage

If all students have attendance above 75%, print a suitable message.

# Concepts to use:

-pandas, DataFrame, groupby(), value_counts(), mean(), max(), min(), sort_values(), iterrows(), Conditional Statements, f-strings

 PRACTICE QUESTIONS:

1. How many students are from the Electronics Department?
2. What is the average attendance of female students?
3. who is the student with the lowest programming score?
4. How many students scored above 80 in math?
5. What  is the average total_score for students with attendance above 90%?

In [4]:
import pandas as pd

# Load dataset
df = pd.read_csv("student_performance.csv")

# Display first 5 rows
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [1]:
print("=" * 50)
print("         STUDENT DATA EXPLORER")
print("=" * 50)

==================================================
         STUDENT DATA EXPLORER
==================================================

In [5]:
print("Dataset Overview")
print("-" * 30)

print(f"Total number of students : {len(df)}")
print(f"Total number of columns  : {len(df.columns)}")
print(f"Unique departments       : {df['department'].nunique()}")

Dataset Overview
------------------------------
Total number of students : 30
Total number of columns  : 13
Unique departments       : 4

In [6]:
print("Department Wise Student Count")
print("-" * 35)

print(df["department"].value_counts())

Department Wise Student Count
-----------------------------------
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [7]:
print("Score Analysis")
print("-" * 30)

print(f"Highest Math Score            : {df['math_score'].max()}")
print(f"Lowest Math Score             : {df['math_score'].min()}")
print(f"Average Math Score            : {df['math_score'].mean():.2f}")
print(f"Average Programming Score     : {df['programming_score'].mean():.2f}")
print(f"Average Attendance Percentage : {df['attendance_percentage'].mean():.2f}%")

Score Analysis
------------------------------
Highest Math Score            : 95
Lowest Math Score             : 56
Average Math Score            : 76.07
Average Programming Score     : 67.60
Average Attendance Percentage : 84.50%

In [9]:
df['total_score']=df['math_score']+df['science_score']+df['english_score']+df['programming_score']
print("Average Total Score by Gender")
print("-" * 40)

print(df.groupby("gender")["total_score"].mean())

Average Total Score by Gender
----------------------------------------
gender
Female    310.666667
Male      280.666667
Name: total_score, dtype: float64

In [10]:
print("Top 5 Performers")
print("-" * 30)

top_students = df.sort_values(by="total_score", ascending=False).head(5)

print(top_students[["name", "department", "total_score"]])

Top 5 Performers
------------------------------
              name        department  total_score
9       Ananya Das  Computer Science          371
21     Tanvi Mehta  Computer Science          367
29  Akanksha Yadav  Computer Science          365
4       Arjun Nair  Computer Science          356
7      Divya Singh  Computer Science          356

In [11]:
print("Students with Attendance Below 75%")
print("-" * 45)

low_attendance = df[df["attendance_percentage"] < 75]

if len(low_attendance) > 0:
    print(low_attendance[["name", "department", "attendance_percentage"]])
else:
    print("All students have attendance above 75%")

Students with Attendance Below 75%
---------------------------------------------
             name   department  attendance_percentage
5     Meera Joshi  Electronics                     72
8    Rahul Mishra   Mechanical                     68
16   Manoj Pandey        Civil                     65
20  Harish Pillai  Electronics                     74
22   Sanjay Dubey        Civil                     70
27  Sunita Pillai        Civil                     73

Practice Questions

In [12]:
electronics_students = df[df["department"] == "Electronics"]

print("Number of students from Electronics Department:", len(electronics_students))

Number of students from Electronics Department: 6

In [13]:
female_attendance = df[df["gender"] == "Female"]["attendance_percentage"].mean()

print(f"Average attendance of female students: {female_attendance:.2f}%")

Average attendance of female students: 88.53%

In [14]:
lowest_programming = df.loc[df["programming_score"].idxmin()]

print("Student with Lowest Programming Score")
print("-" * 40)

print(f"Name : {lowest_programming['name']}")
print(f"Programming Score : {lowest_programming['programming_score']}")

Student with Lowest Programming Score
----------------------------------------
Name : Manoj Pandey
Programming Score : 38

In [15]:
students_above_80 = df[df["math_score"] > 80]

print("Number of students scored above 80 in math:", len(students_above_80))

Number of students scored above 80 in math: 11